name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: 'echo "Hello World!"'
      - name: step-2
        run: 'BRANCH=$(git rev-parse --abbrev-ref HEAD) && echo "Current checked out branch: $BRANCH"'
      
