name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: 'echo "Hello World!"'
      - name: try new command
        run: echo ${{ github.ref_name }}  
      - name: Set Environment Variable
        run: echo "MY_VAR=$([ '${{ github.ref_name }}' == 'main' ] && echo '${{ vars.MY_NEW_VAR_PROD }}' || echo '${{ vars.MY_NEW_VAR_DEV }}')" >> $GITHUB_ENV
      - name: Use Environment Variable
        run: echo $MY_VAR
      
