name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: 'echo "Hello World!"'
      - name: try new command
        run: echo ${{ github.ref_name }}  
      - name: Set Environment Variable
        run: echo "MY_VAR=$([ '${{ github.ref_name }}' == 'refs/heads/main' ] && echo 'Hello from main' || echo 'Hello from dev')" >> $GITHUB_ENV
      - name: Use Environment Variable
        run: echo $MY_VAR
      # - name: Extract branch name
      #   shell: bash
      #   run: echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      #   id: extract_branch
      # - name: use branch name
      #   run: echo ${{ env.BRANCH_NAME }}
      
